version: 1.1.{build}
configuration: Release
assembly_info:
  patch: true
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
build:
  publish_nuget: true
  verbosity: minimal
before_package:
- ps: >-
    (Get-Content "$env:APPVEYOR_BUILD_FOLDER\Konves.Csv\Konves.Csv_net45.nuspec") `
        -replace '<version>[^<]*?</version>', ('<version>{0}</version>' -f $env:APPVEYOR_BUILD_VERSION) |
      Out-File "$env:APPVEYOR_BUILD_FOLDER\Konves.Csv\Konves.Csv_net45.nuspec"